import json, os
from datetime import datetime

class SwordReport:
    def __init__(self, results: dict):
        self.results = results
        self.target = results.get("target", "unknown")
        self.timestamp = datetime.utcnow().strftime("%Y-%m-%d_%H-%M-%S")

    def generate_markdown(self) -> str:
        lines = []
        lines.append(f"# Sword Offensive Report — {self.target}")
        lines.append(f"**Generated:** {self.timestamp}")
        lines.append(f"**Phases:** {', '.join(self.results.get('phases_completed', []))}")
        lines.append("")

        # --- Compliance Section ---
        compliance = self.results.get("_compliance", {})
        if compliance and compliance.get("regulation_breakdown"):
            lines.append("## Compliance Mapping")
            lines.append("")
            lines.append("### Regulation Impact Summary")
            lines.append("")
            lines.append("| Regulation | Controls Affected | Critical | High | Medium |")
            lines.append("|-----------|------------------|----------|------|--------|")
            for reg, data in sorted(compliance.get("regulation_breakdown", {}).items()):
                lines.append(
                    f"| {reg} | {data.get('total_controls_affected', 0)} | "
                    f"{data.get('critical_findings', 0)} | "
                    f"{data.get('high_findings', 0)} | "
                    f"{data.get('medium_findings', 0)} |"
                )
            lines.append("")

            ai_act = compliance.get("ai_act_assessment", {})
            if ai_act:
                lines.append("### EU AI Act Assessment")
                lines.append(f"- **Risk Category:** {ai_act.get('risk_category', 'unknown')}")
                lines.append(f"- **Articles Triggered:**")
                for art in ai_act.get("articles_triggered", []):
                    lines.append(f"  - {art['article']}: {art['title']} — *{art['status']}*")
                lines.append("")

            lines.append("### Mapped Findings by Control")
            lines.append("")
            for mf in compliance.get("mapped_findings", [])[:15]:
                finding = mf.get("finding", {})
                controls = mf.get("compliance_controls", [])
                ctrl_ids = ", ".join(c["control_id"] for c in controls[:3])
                lines.append(
                    f"- **{finding.get('type', 'unknown')}** ({finding.get('severity', '?')}) "
                    f"→ {ctrl_ids}"
                )
            lines.append("")
        # --- End Compliance Section ---

        lines.append("## Summary")
        lines.append(self.results.get("summary", "No summary"))
        lines.append("")

        for phase_name in ["recon", "scan", "exploit", "postex", "exfil", "phish"]:
            phase = self.results.get(phase_name)
            if not phase:
                continue
            lines.append(f"## Phase: {phase_name.upper()}")
            if "error" in phase:
                lines.append(f"**Error:** {phase['error']}")
                lines.append("")
                continue
            for key, value in phase.items():
                if key == "summary":
                    lines.append(f"**Summary:** {value}")
                elif key in ("target", "target_ip", "method") or key.endswith("_count"):
                    lines.append(f"- **{key}:** {value}")
                elif isinstance(value, dict):
                    lines.append(f"- **{key}:** {len(value)} items")
                elif isinstance(value, list):
                    lines.append(f"- **{key}:** {len(value)} items")
                elif isinstance(value, str) and len(value) > 200:
                    lines.append(f"- **{key}:** (truncated, {len(value)} chars)")
                else:
                    lines.append(f"- **{key}:** {value}")
            lines.append("")

        # Validation summary
        validation = self.results.get("validation", {})
        if validation:
            lines.append("## Validation Pipeline")
            lines.append(f"- **Raw findings:** {validation.get('total_raw', 0)}")
            lines.append(f"- **Validated (passed):** {validation.get('total_validated', 0)}")
            lines.append(f"- **Rejected (FP/uncertain):** {validation.get('rejected', 0)}")
            lines.append("")

        lines.append("---")
        lines.append(f"*Report auto-generated by Raphael 2.0 Sword Pipeline*")
        return "\n".join(lines)

    def generate_compliance_json(self) -> dict:
        compliance = self.results.get("_compliance", {})
        if not compliance:
            return {"compliance": "No compliance data available"}
        return {
            "document_type": "Compliance Evidence Package",
            "generated_by": "Raphael 2.0",
            "target": self.target,
            "timestamp": self.timestamp,
            "regulation_breakdown": compliance.get("regulation_breakdown", {}),
            "ai_act_assessment": compliance.get("ai_act_assessment", {}),
            "evidence_summary": compliance.get("evidence_summary", []),
        }

    def generate_html(self) -> str:
        md = self.generate_markdown()
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Sword Report — {self.target}</title>
<style>
body {{ font-family: 'Courier New', monospace; background: #0a0a0a; color: #00ff00; padding: 20px; }}
h1 {{ color: #ff4444; border-bottom: 2px solid #ff4444; }}
h2 {{ color: #ffaa00; margin-top: 30px; }}
pre {{ background: #111; padding: 10px; border-left: 3px solid #00ff00; }}
.summary {{ background: #1a1a2e; padding: 15px; border-radius: 5px; }}
.error {{ color: #ff0000; }}
.meta {{ color: #888; }}
</style>
</head>
<body>
<pre>{md}</pre>
</body>
</html>"""
        return html

    def save(self, directory: str = "/tmp/sword_reports"):
        # AM-4-R2 W-14 (R3.0-P23) shared-sink defense (§4): report artifact
        # writes must not run outside Broker mediation. Fail-closed.
        from orchestrator.auth import enforce_broker_mediation
        enforce_broker_mediation(
            target="sword-report",
            action_type="sword_execute",
            capability="sword.report",
            method="save",
            impact_estimate=5.0,
            path_id="R3.0-P23",
            weld_ticket="W-14",
        )
        os.makedirs(directory, exist_ok=True)
        safe_target = self.target.replace("://", "_").replace("/", "_").replace(":", "_")
        base = os.path.join(directory, f"sword_{safe_target}_{self.timestamp}")

        md_path = base + ".md"
        with open(md_path, "w") as f:
            f.write(self.generate_markdown())

        html_path = base + ".html"
        with open(html_path, "w") as f:
            f.write(self.generate_html())

        json_path = base + ".json"
        with open(json_path, "w") as f:
            json.dump(self.results, f, indent=2, default=str)

        comp_path = base + ".compliance.json"
        with open(comp_path, "w") as f:
            json.dump(self.generate_compliance_json(), f, indent=2)

        return {"markdown": md_path, "html": html_path, "json": json_path, "compliance": comp_path}
